
	SUBDIR =
	SUBDIR += qt5compat
	SUBDIR += qtbase
	SUBDIR += qtcharts
	SUBDIR += qtconnectivity
	SUBDIR += qtdatavis3d
	SUBDIR += qtdeclarative
	SUBDIR += qtimageformats
	SUBDIR += qtlanguageserver
	SUBDIR += qtlottie
	SUBDIR += qtmultimedia
	SUBDIR += qtnetworkauth
	SUBDIR += qtquick3d
	SUBDIR += qtquicktimeline
	SUBDIR += qtremoteobjects
	SUBDIR += qtscxml
	SUBDIR += qtsensors
	SUBDIR += qtserialbus
	SUBDIR += qtserialport
	SUBDIR += qtshadertools
	SUBDIR += qtsvg
	SUBDIR += qttools
	SUBDIR += qttranslations
	SUBDIR += qtwebchannel
	SUBDIR += qtwebsockets

# no support for Wayland in Xenocara
#	 SUBDIR += qtwayland

.include <bsd.port.subdir.mk>
