QT6NAME =		QtSerialBus
COMMENT =		Qt6 API for accessing serial bus devices

SHARED_LIBS +=  Qt6SerialBus              0.0 # 6.3

WANTLIB += ${COMPILER_LIBCXX} Qt6Core Qt6Network c m

.include <bsd.port.mk>
