QT6NAME =		QtNetworKAuth
COMMENT =		Qt6 network authorization components

SHARED_LIBS +=  Qt6NetworkAuth            0.0 # 6.3

WANTLIB += ${COMPILER_LIBCXX} Qt6Core Qt6Network c m

.include <bsd.port.mk>
